# Netlify configuration for a Next.js app in a subdirectory

[build]
  # Tell Netlify to change to the "Frontend" directory before building
  base    = "Frontend"
  # The command and publish dir are typically handled by the Next.js plugin,
  # but we can be explicit.
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Netlify Functions configuration for the Python backend
[functions]
  directory = "backend"
  python_version = "3.9" # Or the desired Python version

# Redirects for API calls to the Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

# The headers below are good security and caching practices.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"